# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/github/super_mario/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/github/super_mario/src/build-linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/github/super_mario/src/build-linux/CMakeFiles /mnt/d/github/super_mario/src/build-linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/github/super_mario/src/build-linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named super_mario

# Build rule for target.
super_mario: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 super_mario
.PHONY : super_mario

# fast build rule for target.
super_mario/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/build
.PHONY : super_mario/fast

controller/game.o: controller/game.cpp.o
.PHONY : controller/game.o

# target to build an object file
controller/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/controller/game.cpp.o
.PHONY : controller/game.cpp.o

controller/game.i: controller/game.cpp.i
.PHONY : controller/game.i

# target to preprocess a source file
controller/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/controller/game.cpp.i
.PHONY : controller/game.cpp.i

controller/game.s: controller/game.cpp.s
.PHONY : controller/game.s

# target to generate assembly for a file
controller/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/controller/game.cpp.s
.PHONY : controller/game.cpp.s

levels/first_level.o: levels/first_level.cpp.o
.PHONY : levels/first_level.o

# target to build an object file
levels/first_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/first_level.cpp.o
.PHONY : levels/first_level.cpp.o

levels/first_level.i: levels/first_level.cpp.i
.PHONY : levels/first_level.i

# target to preprocess a source file
levels/first_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/first_level.cpp.i
.PHONY : levels/first_level.cpp.i

levels/first_level.s: levels/first_level.cpp.s
.PHONY : levels/first_level.s

# target to generate assembly for a file
levels/first_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/first_level.cpp.s
.PHONY : levels/first_level.cpp.s

levels/game_level.o: levels/game_level.cpp.o
.PHONY : levels/game_level.o

# target to build an object file
levels/game_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/game_level.cpp.o
.PHONY : levels/game_level.cpp.o

levels/game_level.i: levels/game_level.cpp.i
.PHONY : levels/game_level.i

# target to preprocess a source file
levels/game_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/game_level.cpp.i
.PHONY : levels/game_level.cpp.i

levels/game_level.s: levels/game_level.cpp.s
.PHONY : levels/game_level.s

# target to generate assembly for a file
levels/game_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/game_level.cpp.s
.PHONY : levels/game_level.cpp.s

levels/second_level.o: levels/second_level.cpp.o
.PHONY : levels/second_level.o

# target to build an object file
levels/second_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/second_level.cpp.o
.PHONY : levels/second_level.cpp.o

levels/second_level.i: levels/second_level.cpp.i
.PHONY : levels/second_level.i

# target to preprocess a source file
levels/second_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/second_level.cpp.i
.PHONY : levels/second_level.cpp.i

levels/second_level.s: levels/second_level.cpp.s
.PHONY : levels/second_level.s

# target to generate assembly for a file
levels/second_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/second_level.cpp.s
.PHONY : levels/second_level.cpp.s

levels/third_level.o: levels/third_level.cpp.o
.PHONY : levels/third_level.o

# target to build an object file
levels/third_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/third_level.cpp.o
.PHONY : levels/third_level.cpp.o

levels/third_level.i: levels/third_level.cpp.i
.PHONY : levels/third_level.i

# target to preprocess a source file
levels/third_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/third_level.cpp.i
.PHONY : levels/third_level.cpp.i

levels/third_level.s: levels/third_level.cpp.s
.PHONY : levels/third_level.s

# target to generate assembly for a file
levels/third_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/levels/third_level.cpp.s
.PHONY : levels/third_level.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/main.cpp.s
.PHONY : main.cpp.s

model/collisionable.o: model/collisionable.cpp.o
.PHONY : model/collisionable.o

# target to build an object file
model/collisionable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/collisionable.cpp.o
.PHONY : model/collisionable.cpp.o

model/collisionable.i: model/collisionable.cpp.i
.PHONY : model/collisionable.i

# target to preprocess a source file
model/collisionable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/collisionable.cpp.i
.PHONY : model/collisionable.cpp.i

model/collisionable.s: model/collisionable.cpp.s
.PHONY : model/collisionable.s

# target to generate assembly for a file
model/collisionable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/collisionable.cpp.s
.PHONY : model/collisionable.cpp.s

model/game_map.o: model/game_map.cpp.o
.PHONY : model/game_map.o

# target to build an object file
model/game_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/game_map.cpp.o
.PHONY : model/game_map.cpp.o

model/game_map.i: model/game_map.cpp.i
.PHONY : model/game_map.i

# target to preprocess a source file
model/game_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/game_map.cpp.i
.PHONY : model/game_map.cpp.i

model/game_map.s: model/game_map.cpp.s
.PHONY : model/game_map.s

# target to generate assembly for a file
model/game_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/game_map.cpp.s
.PHONY : model/game_map.cpp.s

model/movable.o: model/movable.cpp.o
.PHONY : model/movable.o

# target to build an object file
model/movable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable.cpp.o
.PHONY : model/movable.cpp.o

model/movable.i: model/movable.cpp.i
.PHONY : model/movable.i

# target to preprocess a source file
model/movable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable.cpp.i
.PHONY : model/movable.cpp.i

model/movable.s: model/movable.cpp.s
.PHONY : model/movable.s

# target to generate assembly for a file
model/movable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable.cpp.s
.PHONY : model/movable.cpp.s

model/movable_platform.o: model/movable_platform.cpp.o
.PHONY : model/movable_platform.o

# target to build an object file
model/movable_platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable_platform.cpp.o
.PHONY : model/movable_platform.cpp.o

model/movable_platform.i: model/movable_platform.cpp.i
.PHONY : model/movable_platform.i

# target to preprocess a source file
model/movable_platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable_platform.cpp.i
.PHONY : model/movable_platform.cpp.i

model/movable_platform.s: model/movable_platform.cpp.s
.PHONY : model/movable_platform.s

# target to generate assembly for a file
model/movable_platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/movable_platform.cpp.s
.PHONY : model/movable_platform.cpp.s

model/rect.o: model/rect.cpp.o
.PHONY : model/rect.o

# target to build an object file
model/rect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect.cpp.o
.PHONY : model/rect.cpp.o

model/rect.i: model/rect.cpp.i
.PHONY : model/rect.i

# target to preprocess a source file
model/rect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect.cpp.i
.PHONY : model/rect.cpp.i

model/rect.s: model/rect.cpp.s
.PHONY : model/rect.s

# target to generate assembly for a file
model/rect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect.cpp.s
.PHONY : model/rect.cpp.s

model/rect_map_movable_adapter.o: model/rect_map_movable_adapter.cpp.o
.PHONY : model/rect_map_movable_adapter.o

# target to build an object file
model/rect_map_movable_adapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect_map_movable_adapter.cpp.o
.PHONY : model/rect_map_movable_adapter.cpp.o

model/rect_map_movable_adapter.i: model/rect_map_movable_adapter.cpp.i
.PHONY : model/rect_map_movable_adapter.i

# target to preprocess a source file
model/rect_map_movable_adapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect_map_movable_adapter.cpp.i
.PHONY : model/rect_map_movable_adapter.cpp.i

model/rect_map_movable_adapter.s: model/rect_map_movable_adapter.cpp.s
.PHONY : model/rect_map_movable_adapter.s

# target to generate assembly for a file
model/rect_map_movable_adapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/model/rect_map_movable_adapter.cpp.s
.PHONY : model/rect_map_movable_adapter.cpp.s

objects/enemy.o: objects/enemy.cpp.o
.PHONY : objects/enemy.o

# target to build an object file
objects/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/enemy.cpp.o
.PHONY : objects/enemy.cpp.o

objects/enemy.i: objects/enemy.cpp.i
.PHONY : objects/enemy.i

# target to preprocess a source file
objects/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/enemy.cpp.i
.PHONY : objects/enemy.cpp.i

objects/enemy.s: objects/enemy.cpp.s
.PHONY : objects/enemy.s

# target to generate assembly for a file
objects/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/enemy.cpp.s
.PHONY : objects/enemy.cpp.s

objects/flyable_enemy.o: objects/flyable_enemy.cpp.o
.PHONY : objects/flyable_enemy.o

# target to build an object file
objects/flyable_enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/flyable_enemy.cpp.o
.PHONY : objects/flyable_enemy.cpp.o

objects/flyable_enemy.i: objects/flyable_enemy.cpp.i
.PHONY : objects/flyable_enemy.i

# target to preprocess a source file
objects/flyable_enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/flyable_enemy.cpp.i
.PHONY : objects/flyable_enemy.cpp.i

objects/flyable_enemy.s: objects/flyable_enemy.cpp.s
.PHONY : objects/flyable_enemy.s

# target to generate assembly for a file
objects/flyable_enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/flyable_enemy.cpp.s
.PHONY : objects/flyable_enemy.cpp.s

objects/full_box.o: objects/full_box.cpp.o
.PHONY : objects/full_box.o

# target to build an object file
objects/full_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/full_box.cpp.o
.PHONY : objects/full_box.cpp.o

objects/full_box.i: objects/full_box.cpp.i
.PHONY : objects/full_box.i

# target to preprocess a source file
objects/full_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/full_box.cpp.i
.PHONY : objects/full_box.cpp.i

objects/full_box.s: objects/full_box.cpp.s
.PHONY : objects/full_box.s

# target to generate assembly for a file
objects/full_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/full_box.cpp.s
.PHONY : objects/full_box.cpp.s

objects/jumpable_enemy.o: objects/jumpable_enemy.cpp.o
.PHONY : objects/jumpable_enemy.o

# target to build an object file
objects/jumpable_enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/jumpable_enemy.cpp.o
.PHONY : objects/jumpable_enemy.cpp.o

objects/jumpable_enemy.i: objects/jumpable_enemy.cpp.i
.PHONY : objects/jumpable_enemy.i

# target to preprocess a source file
objects/jumpable_enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/jumpable_enemy.cpp.i
.PHONY : objects/jumpable_enemy.cpp.i

objects/jumpable_enemy.s: objects/jumpable_enemy.cpp.s
.PHONY : objects/jumpable_enemy.s

# target to generate assembly for a file
objects/jumpable_enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/jumpable_enemy.cpp.s
.PHONY : objects/jumpable_enemy.cpp.s

objects/mario.o: objects/mario.cpp.o
.PHONY : objects/mario.o

# target to build an object file
objects/mario.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/mario.cpp.o
.PHONY : objects/mario.cpp.o

objects/mario.i: objects/mario.cpp.i
.PHONY : objects/mario.i

# target to preprocess a source file
objects/mario.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/mario.cpp.i
.PHONY : objects/mario.cpp.i

objects/mario.s: objects/mario.cpp.s
.PHONY : objects/mario.s

# target to generate assembly for a file
objects/mario.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/mario.cpp.s
.PHONY : objects/mario.cpp.s

objects/money.o: objects/money.cpp.o
.PHONY : objects/money.o

# target to build an object file
objects/money.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/money.cpp.o
.PHONY : objects/money.cpp.o

objects/money.i: objects/money.cpp.i
.PHONY : objects/money.i

# target to preprocess a source file
objects/money.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/money.cpp.i
.PHONY : objects/money.cpp.i

objects/money.s: objects/money.cpp.s
.PHONY : objects/money.s

# target to generate assembly for a file
objects/money.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/money.cpp.s
.PHONY : objects/money.cpp.s

objects/moving_ship.o: objects/moving_ship.cpp.o
.PHONY : objects/moving_ship.o

# target to build an object file
objects/moving_ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/moving_ship.cpp.o
.PHONY : objects/moving_ship.cpp.o

objects/moving_ship.i: objects/moving_ship.cpp.i
.PHONY : objects/moving_ship.i

# target to preprocess a source file
objects/moving_ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/moving_ship.cpp.i
.PHONY : objects/moving_ship.cpp.i

objects/moving_ship.s: objects/moving_ship.cpp.s
.PHONY : objects/moving_ship.s

# target to generate assembly for a file
objects/moving_ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/objects/moving_ship.cpp.s
.PHONY : objects/moving_ship.cpp.s

os_controls/linux/linux_control_settings.o: os_controls/linux/linux_control_settings.cpp.o
.PHONY : os_controls/linux/linux_control_settings.o

# target to build an object file
os_controls/linux/linux_control_settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_control_settings.cpp.o
.PHONY : os_controls/linux/linux_control_settings.cpp.o

os_controls/linux/linux_control_settings.i: os_controls/linux/linux_control_settings.cpp.i
.PHONY : os_controls/linux/linux_control_settings.i

# target to preprocess a source file
os_controls/linux/linux_control_settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_control_settings.cpp.i
.PHONY : os_controls/linux/linux_control_settings.cpp.i

os_controls/linux/linux_control_settings.s: os_controls/linux/linux_control_settings.cpp.s
.PHONY : os_controls/linux/linux_control_settings.s

# target to generate assembly for a file
os_controls/linux/linux_control_settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_control_settings.cpp.s
.PHONY : os_controls/linux/linux_control_settings.cpp.s

os_controls/linux/linux_keyboard.o: os_controls/linux/linux_keyboard.cpp.o
.PHONY : os_controls/linux/linux_keyboard.o

# target to build an object file
os_controls/linux/linux_keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_keyboard.cpp.o
.PHONY : os_controls/linux/linux_keyboard.cpp.o

os_controls/linux/linux_keyboard.i: os_controls/linux/linux_keyboard.cpp.i
.PHONY : os_controls/linux/linux_keyboard.i

# target to preprocess a source file
os_controls/linux/linux_keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_keyboard.cpp.i
.PHONY : os_controls/linux/linux_keyboard.cpp.i

os_controls/linux/linux_keyboard.s: os_controls/linux/linux_keyboard.cpp.s
.PHONY : os_controls/linux/linux_keyboard.s

# target to generate assembly for a file
os_controls/linux/linux_keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/os_controls/linux/linux_keyboard.cpp.s
.PHONY : os_controls/linux/linux_keyboard.cpp.s

ui/console/console_game_map.o: ui/console/console_game_map.cpp.o
.PHONY : ui/console/console_game_map.o

# target to build an object file
ui/console/console_game_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_game_map.cpp.o
.PHONY : ui/console/console_game_map.cpp.o

ui/console/console_game_map.i: ui/console/console_game_map.cpp.i
.PHONY : ui/console/console_game_map.i

# target to preprocess a source file
ui/console/console_game_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_game_map.cpp.i
.PHONY : ui/console/console_game_map.cpp.i

ui/console/console_game_map.s: ui/console/console_game_map.cpp.s
.PHONY : ui/console/console_game_map.s

# target to generate assembly for a file
ui/console/console_game_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_game_map.cpp.s
.PHONY : ui/console/console_game_map.cpp.s

ui/console/console_ui_factory.o: ui/console/console_ui_factory.cpp.o
.PHONY : ui/console/console_ui_factory.o

# target to build an object file
ui/console/console_ui_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_factory.cpp.o
.PHONY : ui/console/console_ui_factory.cpp.o

ui/console/console_ui_factory.i: ui/console/console_ui_factory.cpp.i
.PHONY : ui/console/console_ui_factory.i

# target to preprocess a source file
ui/console/console_ui_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_factory.cpp.i
.PHONY : ui/console/console_ui_factory.cpp.i

ui/console/console_ui_factory.s: ui/console/console_ui_factory.cpp.s
.PHONY : ui/console/console_ui_factory.s

# target to generate assembly for a file
ui/console/console_ui_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_factory.cpp.s
.PHONY : ui/console/console_ui_factory.cpp.s

ui/console/console_ui_obj_rect_adapter.o: ui/console/console_ui_obj_rect_adapter.cpp.o
.PHONY : ui/console/console_ui_obj_rect_adapter.o

# target to build an object file
ui/console/console_ui_obj_rect_adapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_obj_rect_adapter.cpp.o
.PHONY : ui/console/console_ui_obj_rect_adapter.cpp.o

ui/console/console_ui_obj_rect_adapter.i: ui/console/console_ui_obj_rect_adapter.cpp.i
.PHONY : ui/console/console_ui_obj_rect_adapter.i

# target to preprocess a source file
ui/console/console_ui_obj_rect_adapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_obj_rect_adapter.cpp.i
.PHONY : ui/console/console_ui_obj_rect_adapter.cpp.i

ui/console/console_ui_obj_rect_adapter.s: ui/console/console_ui_obj_rect_adapter.cpp.s
.PHONY : ui/console/console_ui_obj_rect_adapter.s

# target to generate assembly for a file
ui/console/console_ui_obj_rect_adapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/console_ui_obj_rect_adapter.cpp.s
.PHONY : ui/console/console_ui_obj_rect_adapter.cpp.s

ui/console/ui_objects/console_box.o: ui/console/ui_objects/console_box.cpp.o
.PHONY : ui/console/ui_objects/console_box.o

# target to build an object file
ui/console/ui_objects/console_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_box.cpp.o
.PHONY : ui/console/ui_objects/console_box.cpp.o

ui/console/ui_objects/console_box.i: ui/console/ui_objects/console_box.cpp.i
.PHONY : ui/console/ui_objects/console_box.i

# target to preprocess a source file
ui/console/ui_objects/console_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_box.cpp.i
.PHONY : ui/console/ui_objects/console_box.cpp.i

ui/console/ui_objects/console_box.s: ui/console/ui_objects/console_box.cpp.s
.PHONY : ui/console/ui_objects/console_box.s

# target to generate assembly for a file
ui/console/ui_objects/console_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_box.cpp.s
.PHONY : ui/console/ui_objects/console_box.cpp.s

ui/console/ui_objects/console_enemy.o: ui/console/ui_objects/console_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_enemy.o

# target to build an object file
ui/console/ui_objects/console_enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_enemy.cpp.o

ui/console/ui_objects/console_enemy.i: ui/console/ui_objects/console_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_enemy.i

# target to preprocess a source file
ui/console/ui_objects/console_enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_enemy.cpp.i

ui/console/ui_objects/console_enemy.s: ui/console/ui_objects/console_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_enemy.s

# target to generate assembly for a file
ui/console/ui_objects/console_enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_enemy.cpp.s

ui/console/ui_objects/console_flyable_enemy.o: ui/console/ui_objects/console_flyable_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_flyable_enemy.o

# target to build an object file
ui/console/ui_objects/console_flyable_enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_flyable_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_flyable_enemy.cpp.o

ui/console/ui_objects/console_flyable_enemy.i: ui/console/ui_objects/console_flyable_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_flyable_enemy.i

# target to preprocess a source file
ui/console/ui_objects/console_flyable_enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_flyable_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_flyable_enemy.cpp.i

ui/console/ui_objects/console_flyable_enemy.s: ui/console/ui_objects/console_flyable_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_flyable_enemy.s

# target to generate assembly for a file
ui/console/ui_objects/console_flyable_enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_flyable_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_flyable_enemy.cpp.s

ui/console/ui_objects/console_full_box.o: ui/console/ui_objects/console_full_box.cpp.o
.PHONY : ui/console/ui_objects/console_full_box.o

# target to build an object file
ui/console/ui_objects/console_full_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_full_box.cpp.o
.PHONY : ui/console/ui_objects/console_full_box.cpp.o

ui/console/ui_objects/console_full_box.i: ui/console/ui_objects/console_full_box.cpp.i
.PHONY : ui/console/ui_objects/console_full_box.i

# target to preprocess a source file
ui/console/ui_objects/console_full_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_full_box.cpp.i
.PHONY : ui/console/ui_objects/console_full_box.cpp.i

ui/console/ui_objects/console_full_box.s: ui/console/ui_objects/console_full_box.cpp.s
.PHONY : ui/console/ui_objects/console_full_box.s

# target to generate assembly for a file
ui/console/ui_objects/console_full_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_full_box.cpp.s
.PHONY : ui/console/ui_objects/console_full_box.cpp.s

ui/console/ui_objects/console_jumpable_enemy.o: ui/console/ui_objects/console_jumpable_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_jumpable_enemy.o

# target to build an object file
ui/console/ui_objects/console_jumpable_enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_jumpable_enemy.cpp.o
.PHONY : ui/console/ui_objects/console_jumpable_enemy.cpp.o

ui/console/ui_objects/console_jumpable_enemy.i: ui/console/ui_objects/console_jumpable_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_jumpable_enemy.i

# target to preprocess a source file
ui/console/ui_objects/console_jumpable_enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_jumpable_enemy.cpp.i
.PHONY : ui/console/ui_objects/console_jumpable_enemy.cpp.i

ui/console/ui_objects/console_jumpable_enemy.s: ui/console/ui_objects/console_jumpable_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_jumpable_enemy.s

# target to generate assembly for a file
ui/console/ui_objects/console_jumpable_enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_jumpable_enemy.cpp.s
.PHONY : ui/console/ui_objects/console_jumpable_enemy.cpp.s

ui/console/ui_objects/console_mario.o: ui/console/ui_objects/console_mario.cpp.o
.PHONY : ui/console/ui_objects/console_mario.o

# target to build an object file
ui/console/ui_objects/console_mario.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_mario.cpp.o
.PHONY : ui/console/ui_objects/console_mario.cpp.o

ui/console/ui_objects/console_mario.i: ui/console/ui_objects/console_mario.cpp.i
.PHONY : ui/console/ui_objects/console_mario.i

# target to preprocess a source file
ui/console/ui_objects/console_mario.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_mario.cpp.i
.PHONY : ui/console/ui_objects/console_mario.cpp.i

ui/console/ui_objects/console_mario.s: ui/console/ui_objects/console_mario.cpp.s
.PHONY : ui/console/ui_objects/console_mario.s

# target to generate assembly for a file
ui/console/ui_objects/console_mario.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_mario.cpp.s
.PHONY : ui/console/ui_objects/console_mario.cpp.s

ui/console/ui_objects/console_money.o: ui/console/ui_objects/console_money.cpp.o
.PHONY : ui/console/ui_objects/console_money.o

# target to build an object file
ui/console/ui_objects/console_money.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_money.cpp.o
.PHONY : ui/console/ui_objects/console_money.cpp.o

ui/console/ui_objects/console_money.i: ui/console/ui_objects/console_money.cpp.i
.PHONY : ui/console/ui_objects/console_money.i

# target to preprocess a source file
ui/console/ui_objects/console_money.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_money.cpp.i
.PHONY : ui/console/ui_objects/console_money.cpp.i

ui/console/ui_objects/console_money.s: ui/console/ui_objects/console_money.cpp.s
.PHONY : ui/console/ui_objects/console_money.s

# target to generate assembly for a file
ui/console/ui_objects/console_money.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_money.cpp.s
.PHONY : ui/console/ui_objects/console_money.cpp.s

ui/console/ui_objects/console_moving_ship.o: ui/console/ui_objects/console_moving_ship.cpp.o
.PHONY : ui/console/ui_objects/console_moving_ship.o

# target to build an object file
ui/console/ui_objects/console_moving_ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_moving_ship.cpp.o
.PHONY : ui/console/ui_objects/console_moving_ship.cpp.o

ui/console/ui_objects/console_moving_ship.i: ui/console/ui_objects/console_moving_ship.cpp.i
.PHONY : ui/console/ui_objects/console_moving_ship.i

# target to preprocess a source file
ui/console/ui_objects/console_moving_ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_moving_ship.cpp.i
.PHONY : ui/console/ui_objects/console_moving_ship.cpp.i

ui/console/ui_objects/console_moving_ship.s: ui/console/ui_objects/console_moving_ship.cpp.s
.PHONY : ui/console/ui_objects/console_moving_ship.s

# target to generate assembly for a file
ui/console/ui_objects/console_moving_ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_moving_ship.cpp.s
.PHONY : ui/console/ui_objects/console_moving_ship.cpp.s

ui/console/ui_objects/console_ship.o: ui/console/ui_objects/console_ship.cpp.o
.PHONY : ui/console/ui_objects/console_ship.o

# target to build an object file
ui/console/ui_objects/console_ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_ship.cpp.o
.PHONY : ui/console/ui_objects/console_ship.cpp.o

ui/console/ui_objects/console_ship.i: ui/console/ui_objects/console_ship.cpp.i
.PHONY : ui/console/ui_objects/console_ship.i

# target to preprocess a source file
ui/console/ui_objects/console_ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_ship.cpp.i
.PHONY : ui/console/ui_objects/console_ship.cpp.i

ui/console/ui_objects/console_ship.s: ui/console/ui_objects/console_ship.cpp.s
.PHONY : ui/console/ui_objects/console_ship.s

# target to generate assembly for a file
ui/console/ui_objects/console_ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/ui/console/ui_objects/console_ship.cpp.s
.PHONY : ui/console/ui_objects/console_ship.cpp.s

util/format_templates.o: util/format_templates.cpp.o
.PHONY : util/format_templates.o

# target to build an object file
util/format_templates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/format_templates.cpp.o
.PHONY : util/format_templates.cpp.o

util/format_templates.i: util/format_templates.cpp.i
.PHONY : util/format_templates.i

# target to preprocess a source file
util/format_templates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/format_templates.cpp.i
.PHONY : util/format_templates.cpp.i

util/format_templates.s: util/format_templates.cpp.s
.PHONY : util/format_templates.s

# target to generate assembly for a file
util/format_templates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/format_templates.cpp.s
.PHONY : util/format_templates.cpp.s

util/logger.o: util/logger.cpp.o
.PHONY : util/logger.o

# target to build an object file
util/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/logger.cpp.o
.PHONY : util/logger.cpp.o

util/logger.i: util/logger.cpp.i
.PHONY : util/logger.i

# target to preprocess a source file
util/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/logger.cpp.i
.PHONY : util/logger.cpp.i

util/logger.s: util/logger.cpp.s
.PHONY : util/logger.s

# target to generate assembly for a file
util/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_mario.dir/build.make CMakeFiles/super_mario.dir/util/logger.cpp.s
.PHONY : util/logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... super_mario"
	@echo "... controller/game.o"
	@echo "... controller/game.i"
	@echo "... controller/game.s"
	@echo "... levels/first_level.o"
	@echo "... levels/first_level.i"
	@echo "... levels/first_level.s"
	@echo "... levels/game_level.o"
	@echo "... levels/game_level.i"
	@echo "... levels/game_level.s"
	@echo "... levels/second_level.o"
	@echo "... levels/second_level.i"
	@echo "... levels/second_level.s"
	@echo "... levels/third_level.o"
	@echo "... levels/third_level.i"
	@echo "... levels/third_level.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/collisionable.o"
	@echo "... model/collisionable.i"
	@echo "... model/collisionable.s"
	@echo "... model/game_map.o"
	@echo "... model/game_map.i"
	@echo "... model/game_map.s"
	@echo "... model/movable.o"
	@echo "... model/movable.i"
	@echo "... model/movable.s"
	@echo "... model/movable_platform.o"
	@echo "... model/movable_platform.i"
	@echo "... model/movable_platform.s"
	@echo "... model/rect.o"
	@echo "... model/rect.i"
	@echo "... model/rect.s"
	@echo "... model/rect_map_movable_adapter.o"
	@echo "... model/rect_map_movable_adapter.i"
	@echo "... model/rect_map_movable_adapter.s"
	@echo "... objects/enemy.o"
	@echo "... objects/enemy.i"
	@echo "... objects/enemy.s"
	@echo "... objects/flyable_enemy.o"
	@echo "... objects/flyable_enemy.i"
	@echo "... objects/flyable_enemy.s"
	@echo "... objects/full_box.o"
	@echo "... objects/full_box.i"
	@echo "... objects/full_box.s"
	@echo "... objects/jumpable_enemy.o"
	@echo "... objects/jumpable_enemy.i"
	@echo "... objects/jumpable_enemy.s"
	@echo "... objects/mario.o"
	@echo "... objects/mario.i"
	@echo "... objects/mario.s"
	@echo "... objects/money.o"
	@echo "... objects/money.i"
	@echo "... objects/money.s"
	@echo "... objects/moving_ship.o"
	@echo "... objects/moving_ship.i"
	@echo "... objects/moving_ship.s"
	@echo "... os_controls/linux/linux_control_settings.o"
	@echo "... os_controls/linux/linux_control_settings.i"
	@echo "... os_controls/linux/linux_control_settings.s"
	@echo "... os_controls/linux/linux_keyboard.o"
	@echo "... os_controls/linux/linux_keyboard.i"
	@echo "... os_controls/linux/linux_keyboard.s"
	@echo "... ui/console/console_game_map.o"
	@echo "... ui/console/console_game_map.i"
	@echo "... ui/console/console_game_map.s"
	@echo "... ui/console/console_ui_factory.o"
	@echo "... ui/console/console_ui_factory.i"
	@echo "... ui/console/console_ui_factory.s"
	@echo "... ui/console/console_ui_obj_rect_adapter.o"
	@echo "... ui/console/console_ui_obj_rect_adapter.i"
	@echo "... ui/console/console_ui_obj_rect_adapter.s"
	@echo "... ui/console/ui_objects/console_box.o"
	@echo "... ui/console/ui_objects/console_box.i"
	@echo "... ui/console/ui_objects/console_box.s"
	@echo "... ui/console/ui_objects/console_enemy.o"
	@echo "... ui/console/ui_objects/console_enemy.i"
	@echo "... ui/console/ui_objects/console_enemy.s"
	@echo "... ui/console/ui_objects/console_flyable_enemy.o"
	@echo "... ui/console/ui_objects/console_flyable_enemy.i"
	@echo "... ui/console/ui_objects/console_flyable_enemy.s"
	@echo "... ui/console/ui_objects/console_full_box.o"
	@echo "... ui/console/ui_objects/console_full_box.i"
	@echo "... ui/console/ui_objects/console_full_box.s"
	@echo "... ui/console/ui_objects/console_jumpable_enemy.o"
	@echo "... ui/console/ui_objects/console_jumpable_enemy.i"
	@echo "... ui/console/ui_objects/console_jumpable_enemy.s"
	@echo "... ui/console/ui_objects/console_mario.o"
	@echo "... ui/console/ui_objects/console_mario.i"
	@echo "... ui/console/ui_objects/console_mario.s"
	@echo "... ui/console/ui_objects/console_money.o"
	@echo "... ui/console/ui_objects/console_money.i"
	@echo "... ui/console/ui_objects/console_money.s"
	@echo "... ui/console/ui_objects/console_moving_ship.o"
	@echo "... ui/console/ui_objects/console_moving_ship.i"
	@echo "... ui/console/ui_objects/console_moving_ship.s"
	@echo "... ui/console/ui_objects/console_ship.o"
	@echo "... ui/console/ui_objects/console_ship.i"
	@echo "... ui/console/ui_objects/console_ship.s"
	@echo "... util/format_templates.o"
	@echo "... util/format_templates.i"
	@echo "... util/format_templates.s"
	@echo "... util/logger.o"
	@echo "... util/logger.i"
	@echo "... util/logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

